# Generated by Django 4.1.3 on 2023-10-01 04:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("name",)},
        ),
    ]
